name: beam_messenger
description: A new flutter project.

dependencies:
  local_auth: "^0.2.0"
  shared_preferences: "^0.4.0"
  cupertino_icons: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true