name: beam_messenger
description: A new flutter project.

dependencies:
  http: any
  sqflite: any
  path_provider: any
  cupertino_icons: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/login_background.jpg